### ISSUE TITLE
osx failed to install parity 1.6.3 (worked with 1.5.11)

### ISSUE THREAD

**Issue by connectdotz** [paritytech/homebrew-paritytech#39]
I was trying to upgrade from 1.5.11 (stable) to 1.6.3. the brew failed for 1.6.3 (was able to install 1.5.11):

```
$ brew install parity
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
magic-wormhole
==> Updated Formulae
django-completion        jsonschema2pojo          numpy                    screenfetch              sjk                      zinc
gitlab-ci-multi-runner   kobalt                   pwntools                 shairport-sync           sysdig

==> Installing parity from ethcore/ethcore
==> Cloning https://github.com/ethcore/parity.git
Updating /Users/xxxx/Library/Caches/Homebrew/parity--git
==> Checking out tag v1.6.3
==> multirust update stable
==> multirust run stable cargo build --release
Last 15 lines from /Users/xxxx/Library/Logs/Homebrew/parity/02.multirust:
   Compiling lazycell v0.4.0
error[E0277]: the trait bound `&&std::vec::Vec<std::string::String>: std::iter::Iterator` is not satisfied
   --> .brew_home/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.6.2/build.rs:227:10
    |
227 |         .args(&args)
    |          ^^^^ the trait `std::iter::Iterator` is not implemented for `&&std::vec::Vec<std::string::String>`
    |
    = note: `&&std::vec::Vec<std::string::String>` is not an iterator; maybe try calling `.iter()` or a similar method
    = note: required because of the requirements on the impl of `std::iter::IntoIterator` for `&&std::vec::Vec<std::string::String>`

error: aborting due to previous error

error: Could not compile `ring`.
Build failed, waiting for other jobs to finish...
error: build failed

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethcore/homebrew-ethcore/issues

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:226:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:184:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:233:in `issues_matching'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:266:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:338:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:334:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:396:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:130:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
```

**Comment by debris** [comment]
we use prebuilt binaries now, closing
